---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3 and dependencies (Debian/Ubuntu)
      ansible.builtin.raw: apt-get update && apt-get install -y python3 python3-cryptography
      changed_when: false

    - name: Install python3 and dependencies (RedHat)
      ansible.builtin.raw: command -v dnf && dnf install -y python3 python3-cryptography || yum install -y python3 python3-cryptography
      changed_when: false
      ignore_errors: true
